### ISSUE TITLE
Make the Nav Bar Mobile Responsive in React/Next 

### ISSUE THREAD

**Issue by Sahil4883** [Sahil4883/quiz-card#1]
The Navigation Bar in made with Tailwind CSS and is working on the web view and mobile responsiveness is needed as the hamburger button is clicked the side menu in mobile view pops up and show the current Links and a Close button added to close the Navigation Bar

How to run the project on your own machine?
=> Please go through the documentation 

How you'll see the Nav File?
=>The Nav file is located in the Components folder and only that is needed to be changed

**Comment by avinash-24-aptrix** [comment]
I am willing to contribute
